### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by DRCRecoveryData** [albmac/JPEGVisualRepairTool#1]
Hi,

I have made python to repair encrypted file but after i shift mcu block the final image have glitch of mcu collum because the mcu from left higher than the last mcu row, can i sent file and script private via your email?

**Comment by albmac** [comment]
Sorry, what do you mean with "glitch of mcu collum"?

**Comment by DRCRecoveryData** [comment]
> Sorry, what do you mean with "glitch of mcu collum"?

From step 1, i move the good header from same camera file to encrypted file by main1.py

https://replit.com/@cuuhodrc/Python-1?mobileWebview=1&mobileBridge=1&hideBottomBar=1&hideChatInput=1&supportsUpsellBridge=1&forceTheme=replitLight&fun=1#test/Repaired/_NHL0591.JPG

step 2:

So if file encrypted by ransomware the mcu will wrong and image have wrong allignment, so i decide to fix allgin by remove all the gray mcu from that bottom of image, you can see after remove all non mcu scan-line the shift mcu have count the non-mcu from last scan-line to shift mcu
i will run the main8.py with previous repaired jpeg:

https://replit.com/@cuuhodrc/Python-1?mobileWebview=1&mobileBridge=1&hideBottomBar=1&hideChatInput=1&supportsUpsellBridge=1&forceTheme=replitLight&fun=1#Repaired/_NHL0591.JPG

you can see the left mcu collum is glitch and higher 1 mcu collum than other

**Comment by albmac** [comment]
It seems that the right "segment" of the image belongs to the left side, so it's a matter of usual image editing.
The original MCUs have been already modified so it's not possible to use JVRT.
Maybe it was simply rotated?

**Comment by DRCRecoveryData** [comment]
> It seems that the right "segment" of the image belongs to the left side, so it's a matter of usual image editing. The original MCUs have been already modified so it's not possible to use JVRT. Maybe it was simply rotated?

As i explain maybe hard when use text, but the last scanline before shift mcu have glitch i think count the last scan row have non mcu number then insert mcu to block 0 so image will alligned

**Comment by albmac** [comment]
Please load the image with JVRT and show the result.

**Comment by albmac** [comment]
Please use discussions
