### ISSUE TITLE
Pasting, Ctrl+v, should overwrite, not insert MCUs.

### ISSUE THREAD

**Issue by crass** [albmac/JPEGVisualRepairTool#10]
The current action of Ctrl+v should instead be ctrl+i (for insert, but perhaps that should be linked to the "insert MCU" button and a different character should be used for "insert and paste"). I think this is more intuitive when coming from other image editors.

**Comment by albmac** [comment]
From my usage experience it is very rare that you want to directly replace selected MCUs with paste; it is generally safer to first insert then delete.
Also in text applications you insert with ctrl-v, and never override unless some text was already selected.
