### ISSUE TITLE
Visibly disable tools element while in the busy state

### ISSUE THREAD

**Issue by crass** [albmac/JPEGVisualRepairTool#11]
Currently while in the busy state buttons do not work, which is good, but its not obvious to the user that they are effectively disabled. The one indicator I have found is the highlighted edge around the selected MCU disappears until the busy state is finished. This is very subtle and, depending on zoom level, may not be that noticeable.

**Comment by albmac** [comment]
A spinner was added to the last commit to indicate when busy
