### ISSUE TITLE
Allowing editing MCU values

### ISSUE THREAD

**Issue by crass** [albmac/JPEGVisualRepairTool#6]
Due to an intermittently failing sdcard, I was able to get several copies of a corrupt image where the corruption appears in different MCUs. I would like to be able copy/paste or enter the MCU values from a good MCU to replace the bad MCU values.

**Comment by crass** [comment]
It turns out MCUs can be copied from an image in one tab to an image in another tab in the same browser instance. So this covers my use case. Leaving this open for now, because perhaps there's some value in entering by hand MCU values(?).

**Comment by albmac** [comment]
I don't think a manual edit is useful.
